### ISSUE TITLE
Opencast Studio fails to set duration

### ISSUE THREAD

**Issue by loewis** [elan-ev/opencast-studio#578] opened 2020-04-22 09:53 UTC
Apparently, Opencast Studio fails to fill out the duration of the recording. As a consequence, the admin-ng UI displays 00:00:00 as the duration (for any recording through studio). As another consequence, the Moodle block produces a runtime error,see

https://github.com/unirz-tu-ilmenau/moodle-block_opencast/issues/128

It's because of that error (property undefined) that I think that the duration simply is not set (rather than being set to 0).

**Comment by LukasKalbertodt** [comment] 2020-04-22 17:15
We already know about [this problem](https://github.com/elan-ev/opencast-studio/issues/517), but I'm not sure if that's the same thing you are talking about. Could you try this with Firefox and check if the issue still occurs? If not, then we can close this issue in favor of #517, if yes, this is very likely a problem with the Opencast side and not Studio.

**Comment by LukasKalbertodt** [comment] 2020-04-29 08:48
Closing as dupe of #517 or as "not part of studio". If you meant something else, just comment and I will reopen :)

**Closed by LukasKalbertodt** 2020-04-29 08:48 UTC
