### ISSUE TITLE
Select webcam if more than one exists

### ISSUE THREAD

**Issue by darolfes** [elan-ev/opencast-studio#31] opened 2019-07-03 16:27 UTC

**Comment by luniki** [comment] 2019-09-26 20:19
Shouldn't this be done by the user using the dialog from the user agent?

**Comment by darolfes** [comment] 2019-09-30 17:09
I don't know the details, this was only reported to me. You probably need to test this with multiple webcams.

**Comment by luniki** [comment] 2019-10-01 08:13
I tested this in desktop and mobile environments but could not reproduce any problems. I close this for now until we get more detailed error reports.

**Closed by luniki** 2019-10-01 08:13 UTC
Labels: question
