### ISSUE TITLE
No option to cancel configuration

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#89] opened 2019-10-14 22:51 UTC
If you open the configuration dialog and change something, there is no option to cancel the configuration, discard the changes and revert to the previous settings.

<img src="https://user-images.githubusercontent.com/1008395/66787452-0a0ba400-eee4-11e9-9f9d-803a0de51b35.png" width="300"/>

**Comment by luniki** [comment] 2019-10-22 08:26
Duplicate of #90

**Closed by luniki** 2019-10-22 08:26 UTC
