### ISSUE TITLE
Manifest: Line: 1, column: 1, Syntax error.

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#513] opened 2020-03-25 20:23 UTC
…appears in the Chrome console though it does not seem to cause an actual error.

**Comment by LukasKalbertodt** [comment] 2020-03-26 12:07
I've seen this multiple times already, but I can't reproduce it right now. If anyone knows how to reproduce this, please tell us!

**Comment by lkiesow** [comment] 2020-03-31 20:46
Happens every time I use Chromium or Chrome with the integrated Studio e.g. on https://develop.opencast.org/studio/

**Comment by LukasKalbertodt** [comment] 2020-03-31 20:55
Ah yeah, now I could reproduce it. 

As suspected, this is the same underlying problem as with [this issue](https://github.com/opencast/opencast/issues/1495). The request for `manifest.json` is done without cookies by the browser. Thus, Opencast returns 302 and then the login page (not valid JSON!!).

From [this SO post](https://stackoverflow.com/a/57184506/2408867) it seems like we can instruct the browser to include cookies in the request for `manifest.json`. The question is: do we want that? Or should I also just make `manifest.json` available to anyone when I fix https://github.com/opencast/opencast/issues/1495?

**Comment by lkiesow** [comment] 2020-03-31 21:30
There isn't anything secret in there, is there? So we can just make it public.

**Comment by LukasKalbertodt** [comment] 2020-04-06 21:10
Fixed by https://github.com/opencast/opencast/pull/1509

**Closed by LukasKalbertodt** 2020-04-06 21:10 UTC
Labels: B-chrome, low-priority
