### ISSUE TITLE
New Recording, when open settings

### ISSUE THREAD

**Issue by jqr86** [elan-ev/opencast-studio#557] opened 2020-04-10 08:04 UTC
Instructions for reproducing the problem:

1.) Start recording with screen and sound in Opencast Studio.
2.) Press the red recording button
3.) Time is running.
4.) Switch to setting
5.) Back to recording
6.) Time stops running
7.) Press the red record button again
8.) Stop recording after a while and continue

-> System creates two records. Both are possible to download with different lengths of time.

If you repeat steps 4 - 7 more often, you will get an error.

Internal error: too few or too many video streams

**Comment by LukasKalbertodt** [comment] 2020-04-10 08:28
Thanks for the bug report! This explains another bug report I received and that I couldn't find the cause for, so thanks a bunch. 

Fortunately, I already fixed that bug or rather: make it impossible for the user to switch to settings during recording. Please check out [the version of the current `master` branch](https://test.studio.opencast.org/build-20200409155249-elan-ev-opencast-studio-001769-master/). There you should see the menu bar grayed out while recording. Please let me know if this solves the problem for you.

**Comment by LukasKalbertodt** [comment] 2020-04-21 06:24
This was released in 2020-04-20. I'll just assume the bug was fixed and close this. If that turns out not to be the case, we can still reopen.

**Closed by LukasKalbertodt** 2020-04-21 06:24 UTC
Labels: bug
