### ISSUE TITLE
Audio-only recording

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#616] opened 2020-05-12 08:48 UTC
Sometimes you want audio only in which case it would be nice to be able to select “No Video” in the first step instead of manually removing it from the container later.

**Comment by LukasKalbertodt** [comment] 2020-05-12 09:11
Dupe of https://github.com/elan-ev/opencast-studio/issues/396 ;-)

**Closed by LukasKalbertodt** 2020-05-12 09:11 UTC
Labels: C-new-feature
