### ISSUE TITLE
Limit preview size to device size

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#77] opened 2019-10-14 21:32 UTC
Especially on smaller devices, it may easily happen that the preview video size exceeds the display size making it impossible to see the whole preview. Independent from the specific device, it would hence make sense to always limit the preview size to the device size.

Example:
<img src="https://user-images.githubusercontent.com/1008395/66784350-7c778680-eeda-11e9-828b-9cfe956e9caf.jpg" width="300"/>

**Comment by LukasKalbertodt** [comment] 2019-11-19 14:40
I can't reproduce this anymore. I also tried Firefox on Android and while it is certainly not perfect yet (the record button is partially out of the viewport), the video preview is always fully visible. Maybe this was also fixed by #184?

**Comment by LukasKalbertodt** [comment] 2019-11-22 10:32
I'm gonna close this, as I couldn't reproduce it with any device/browser.

**Closed by LukasKalbertodt** 2019-11-22 10:32 UTC
