### ISSUE TITLE
“Home”-Button does not work on upload page

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#392] opened 2020-02-05 13:53 UTC
After uploading a video, if you click on the logo in the top-left corner, nothing happens. I would expect to end up on the landing page instead.

**Comment by LukasKalbertodt** [comment] 2020-02-07 15:32
Is this really what we want though? For one, when you are already recording, you don't want to accidentally discard anything. But even when you are not recording yet, going back to the start page requires 3 clicks/taps ("back", "back", "reselect sources"). That's not too bad IMO, especially given that I don't expect that action to be very frequent. And *if* we think users frequently want to go back to the start from recording-view, *then* it shouldn't be done over the logo, as many "normal" users don't expect the logo to do that. 

So while I understand why you (as experienced user) expect the behavior you describe, I'd argue the current behavior "works as intended" and we shouldn't change it. I think.

**Comment by LukasKalbertodt** [comment] 2020-03-17 09:43
Will close this as "won't fix, intended behavior" right now. We can of course discuss this in the future again, once we have a bit more time.

**Closed by LukasKalbertodt** 2020-03-17 09:43 UTC
