### ISSUE TITLE
Aduio Pegel Preview in Simple Mode

### ISSUE THREAD

**Issue by CGreweling** [elan-ev/opencast-studio#1] opened 2019-06-07 08:38 UTC
To have somwhere a small Audiopegel Preview would be nice.

**Comment by rrolf** [comment] 2019-06-24 09:43
By the way: is the blue point in advanded mode next to the mic icon an audio meter? Then it is broken at least in Chrome

**Comment by darolfes** [comment] 2019-07-03 16:02
related #30 and #10

**Comment by luniki** [comment] 2019-10-01 09:41
Duplicate of #30

**Closed** 2019-10-01 09:41 UTC
Labels: enhancement
