### ISSUE TITLE
Processing in Opencast fails when the beginning of the video is cut.

### ISSUE THREAD

**Issue by narickmann** [elan-ev/opencast-studio#1049] opened 2023-06-02 13:34 UTC
When you cut the video only at the start/beginning the processing in Opencast fails. 
When you cut it only at the end or on both sides, it's fine.  

Not sure if it's a Studio related Issue (problem with smil/cutting informations being sent to Opencast?) or an Opencast related issue. 
If it is an Opencast related issue, I will open an issue for Opencast.

How to reproduce:
- Record a video in Studio
- Cut the video only at the beginning
- Upload to Opencast
- See processing failure in Opencast

![grafik](https://github.com/elan-ev/opencast-studio/assets/93541078/b64073e7-38f1-4920-ab46-9245bbc71bd3)

![grafik](https://github.com/elan-ev/opencast-studio/assets/93541078/ff1e5641-f0e2-48a4-a662-fee0407773d9)

**Comment by LukasKalbertodt** [comment] 2023-06-06 07:01
I can't reproduce that :/ Tried to set the start marker at 0.1s and another time at 1.2s or so. Both times it worked fine. Does it have to be dual stream? If you can reproduce it again, please download the SMIL attachment from the admin UI and paste it here.

**Comment by LukasKalbertodt** [comment] 2023-08-24 15:19
I will close this for now as we don't have a reproducible example. If you investigate this again, feel free to reopen.

**Closed by LukasKalbertodt** 2023-08-24 15:19 UTC
