### ISSUE TITLE
Duplicate upload

### ISSUE THREAD

**Issue by mtneug** [elan-ev/opencast-studio#566] opened 2020-04-14 14:18 UTC
I just have seen the following in our production system:

![image](https://user-images.githubusercontent.com/3051721/79234599-c54ccf80-7e6a-11ea-8f5b-6e90cee02b3a.png)

I'm not sure how the user managed to do this, but the files were uploaded twice. This, later on, leads to error in our workflows.

**Comment by LukasKalbertodt** [comment] 2020-04-15 09:24
> I'm not sure how the user managed to do this

Neither am I, unfortunately. I was made aware of a similar case at our university recently. This might be caused by [this bug](https://github.com/elan-ev/opencast-studio/issues/557), but I am not sure. I recently added a few checks in several places to make this error less likely: https://github.com/elan-ev/opencast-studio/pull/552

I'd close this issue for now. If you see this happen again with a Studio version that includes #552, let me know and we can reopen this and investigate.

**Closed by LukasKalbertodt** 2020-04-15 09:24 UTC

**Comment by mtneug** [comment] 2020-04-15 09:34
I'm pretty sure this was with a version before #552, but I yesterday I deployed from master. Will let you know.
